project/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

project/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    #デフォルトのURLでは拠点一覧を表示
    path('base/', views.BaseList.as_view(), name='base_list'),

    #<int:pk>にはBaseModelのnameに割り振られた数値が設定される
    path('base/<int:pk>/seat/', views.SeatList.as_view(), name='seat_list'),

    #日付未指定の場合は当日、日付指定の場合は該当日でのカレンダー表示
    path('base/<int:pk>/calendar/', views.SeatList.as_view(), name='calendar'),
    path('base/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/', views.SeatList.as_view(), name='calendar'),

    path('base/<int:pk>/booking/<int:no>/<int:year>/<int:month>/<int:day>/', views.Booking.as_view(), name='booking'),

    path('scheduledelete/<int:pk>/delete/', views.ScheduleDelete.as_view(), name='scheduledelete'),

    #path('scheduledelete/<int:pk>/delete/<int:no>/<int:year>/<int:month>/<int:day>/', views.ScheduleDelete.as_view(), name='scheduledelete'),
    
    #path('base/<int:pk>/scheduledelete/<int:no>/<int:year>/<int:month>/<int:day>/', views.ScheduleDelete.as_view(), name='scheduledelete'),
    #path('base/<int:pk>/booking/<int:no>/<int:year>/<int:month>/<int:day>/scheduledelete/<int:sche>/', views.ScheduleDelete.as_view(), name='scheduledelete'),

    #錦糸町座席表 表示用URL
    path('base/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/Map1/', views.SeatMap1.as_view(), name='SeatMap1'),
    #錦糸町座席表 表示用URL
    path('base/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/Map2/', views.SeatMap2.as_view(), name='SeatMap2'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

# 画像データを表示するためのimport
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/app/templates/app/base_list.html
{% extends 'app/top.html' %}

{% block content %}

<style type="text/css">
    .card{
    animation: fadein 1s forwards;
    }
    
    @keyframes fadein {
        0% {opacity: 0}
        100% {opacity: 1}
    }    
</style>

<center>
<div class="card" style="width: 800px;">
    <h2 class="card-header">拠点一覧</h2>
        <div class="card-body">
        <ul>
            {% for base in base_list %}
                <h3><a href="{% url 'app:calendar' base.pk %}">{{ base.name }}</h3></p>
            {% empty %}
                <li>拠点登録がありません</li>
            {% endfor %}
        </ul>
    </div>
</div>
</center>
{% endblock %}

project/app/templates/app/booking.html
{% extends 'app/top.html' %}

{% block content %}

<style type="text/css">
    .warp{
    animation: fadein 1s forwards;
    }
    
    @keyframes fadein {
        0% {opacity: 0}
        100% {opacity: 1}
    }    
</style>

<div class="warp">

<center>
    <h4>以下の内容で予約します。</h4>
    <img src="/media/279+socio.jpg" width="10%" height="10%" border="0" />
    <h4>日程：{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日</h4>
    <h4>座席：{{ seatno }}</h4>
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
</center>

</div>
{% endblock %}

project/app/templates/app/calendar.html
{% extends 'app/top.html' %}

{% block content %}

<style type="text/css">
    .card{
    animation: fadein 1s forwards;
    }
    
    @keyframes fadein {
        0% {opacity: 0}
        100% {opacity: 1}
    }    
</style>

<div class="card">
    <h2 class="card-header">{{ base.name }} 座席</h2>
    <h4>　{{ start_day|date:"Y/n/j" }} - {{ end_day|date:"Y/n/j" }}</h4>
    <!-- 拠点の座席表表示 -->
    {% if base.map %}
    <center>
    <p class="nav-item"><img src="{{ base.map.url }}" alt=""></p>
    </center>
    {% endif %}
    <table class="table table-bordered text-center" style="table-layout: fixed;width: 100%" border="0">
        <tr>
            <td><a href="{% url 'app:calendar' base.pk before.year before.month before.day %}">前週</a></td>
            {% for day in days %}
                {% if day in public_holidays %}
                    <!-- 祝日の際の設定表示設定 -->
                    <th style="background-color: lightyellow">
                        {% if base.pk == 1 %}
                            <a href="{% url 'app:SeatMap1' base.pk day.year day.month day.day %}">{{ day | date:"d(D)" }}</a>
                        {% elif base.pk == 2 %}
                            <a href="{% url 'app:SeatMap2' base.pk day.year day.month day.day %}">{{ day | date:"d(D)" }}</a>
                        {% endif %}
                    </th>
                {% elif day.weekday == 5 %}
                    <th style="background-color: rgb(199, 231, 250)">
                        {% if base.pk == 1 %}
                            <a href="{% url 'app:SeatMap1' base.pk day.year day.month day.day %}">{{ day | date:"d(D)" }}</a>
                        {% elif base.pk == 2 %}
                            <a href="{% url 'app:SeatMap2' base.pk day.year day.month day.day %}">{{ day | date:"d(D)" }}</a>
                        {% endif %}
                    </th>
                {% elif day.weekday == 6 %}
                    <th style="background-color: rgb(252, 204, 204)">
                        {% if base.pk == 1 %}
                            <a href="{% url 'app:SeatMap1' base.pk day.year day.month day.day %}">{{ day | date:"d(D)" }}</a>
                        {% elif base.pk == 2 %}
                            <a href="{% url 'app:SeatMap2' base.pk day.year day.month day.day %}">{{ day | date:"d(D)" }}</a>
                        {% endif %}
                    </th>
                {% else %}
                    <th style="background-color: rgb(215, 247, 215)">
                        {% if base.pk == 1 %}
                            <a href="{% url 'app:SeatMap1' base.pk day.year day.month day.day %}">{{ day | date:"d(D)" }}</a>
                        {% elif base.pk == 2 %}
                            <a href="{% url 'app:SeatMap2' base.pk day.year day.month day.day %}">{{ day | date:"d(D)" }}</a>
                        {% endif %}
                    </th>
                {% endif %}
            {% endfor %}
            <td><a href="{% url 'app:calendar' base.pk next.year next.month next.day %}">次週</a></td>
        </tr>

        {% for seat, schedule in calendar.items %}
            <tr style="font-size:15px">
                <td>
                    <b>{{ seat }}</b>
                    </td>
                        {% for dt, schedule in schedule.items %}
                            <td>
                                {% if schedule == "none" %}
                                    <a href="{% url 'app:booking' base.pk seat.pk dt.year dt.month dt.day %}">○</a>
                                {% else %}
                                    <a href="{% url 'app:scheduledelete' sche.pop %}">{{ schedule }}</a>
                                {% endif %}
                            </td>
                        {% endfor %}
                    <td>
                    <b>{{ seat }}</b>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

project/app/templates/app/scheduledelete.html
{% extends 'app/top.html' %}

{% block content %}
<style type="text/css">
    .warp{
    animation: fadein 1s forwards;
    }
    
    @keyframes fadein {
        0% {opacity: 0}
        100% {opacity: 1}
    }    
</style>

<div class="warp">

<center>
    <h1>{{ seatno }}</h1>
    <h5>予約を削除しますか</h5>
    <img src="/media/32+fu.jpg" width="10%" height="10%" border="0" />
    <form method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
</center>

</div>

{% endblock %}

project/app/templates/app/scheduledetail.html
{{ object.date }}
{{ object.user }}
{{ object.base }}
{{ object.seat }}

project/app/templates/app/seat_list.html
{% extends 'app/top.html' %}

{% block content %}
    <h1>{{ base.name }}座席一覧</h1>
    <body>
        {{ request }}
        serch: {{ age }}
    </body>
    <ul>
        {{c_queryset}}
        {% for seat in seat_list %}
            <li><a href="">{{ seat.seatno }}</a></li>
        {% empty %}
            <li>座席の登録がありません</li>
        {% endfor %}
    </ul>
{% endblock %}

project/app/templates/app/seatmap1.html
{% extends 'app/top.html' %}

{% block content %}
<style type="text/css">
/*錦糸町 座席用設定*/
    /*++++ 外枠 ++++*/
    .panelbox1{
        /* flex レイアウト設定 */
        display: flex;
        flex-flow: row wrap;
        align-items: stretch;
        justify-content: flex-end;
        /* ボックス設定 */
        width: 500px;
        margin: 20px auto;
    }
 
    /*++++ パネル ++++*/
    .panelbox1 a{
        /* flex レイアウト設定 */
        flex: 0 0 auto;
        /* ボックス設定 */
        display: flex;
        justify-content: flex-end;
        display: block;
        width: 100px;
        height:75px; line-height: 50px;
        margin: 3px auto;
        box-sizing: border-box;
        border: solid 2px rgb(126, 126, 126);
        border-radius: 4px;
        /* テキスト設定 */
        text-align: center;
        text-decoration: none;
    }

    .panelbox1_{
        /* flex レイアウト設定 */
        display: flex;
        flex-flow: row wrap;
        align-items: stretch;
        justify-content: start;
        /* ボックス設定 */
        width: 200px;
        margin: 20px auto;
    }
    /*++++ パネル ++++*/
    .panelbox1_ a{
        /* flex レイアウト設定 */
        flex: 0 0 auto;
        /* ボックス設定 */
        display: flex;
        justify-content: start;
        display: block;
        width: 100px;
        height:75px; line-height: 50px;
        margin: 3px auto;
        box-sizing: border-box;
        border: solid 2px rgb(126, 126, 126);
        border-radius: 4px;
        /* テキスト設定 */
        text-align: center;
        text-decoration: none;
    }

    .card {
	animation: fadein 1s forwards;
    }

    @keyframes fadein {
	    0% {opacity: 0}
	    100% {opacity: 1}
    }

</style>

    <div class="card">
        <h2 class="card-header">{{ base.name }} 座席</h2>
        <h4>　{{ start_day|date:"Y/n/j" }}</h4>
        <div class="panelbox1">
            {% for seat, schedule in calendar.items %}
                {% if forloop.counter > 0 and forloop.counter <= 10 %}
                    {% for dt, schedule in schedule.items %}
                        {% if schedule == "none" %}
                            <a href="{% url 'app:booking' base.pk seat.pk dt.year dt.month dt.day %}">{{ seat }}○</a>
                        {% else %}
                            <a href="{% url 'app:scheduledelete' sche.pop %}">{{ schedule }}</a>
                        {% endif %} 
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </div>
        <div class="panelbox1_">
            {% for seat, schedule in calendar.items %}
                {% if forloop.counter >= 11 and forloop.counter <= 20 %}
                    {% for dt, schedule in schedule.items %}
                        {% if schedule == "none" %}
                            <a href="{% url 'app:booking' base.pk seat.pk dt.year dt.month dt.day %}">{{ seat }}○</a>
                        {% else %}
                            <a href="{% url 'app:scheduledelete' sche.pop %}">{{ schedule }}</a>
                        {% endif %} 
                    {% endfor %}
                {% endif %}
            {% endfor %}
    </div>

{% endblock %}

project/app/templates/app/seatmap2.html
{% extends 'app/top.html' %}

{% block content %}

<style type="text/css">
/*飯田橋 座席用設定*/
    /*++++ 外枠 ++++*/
    .panelbox2{
        /* flex レイアウト設定 */
        display: flex;
        flex-flow: row wrap;
        align-items: stretch;
        justify-content: space-around;
        /* ボックス設定 */
        width: 600px;
        margin: 20px auto; 
    }

    /*++++ パネル ++++*/
    .panelbox2 a{
        /* flex レイアウト設定 */
        flex: 0 0 auto;
        /* ボックス設定 */
        display: block;
        width: 120px;
        height:65px; line-height: 50px;
        margin: 0px auto;
        box-sizing: border-box;
        border: solid 2px rgb(126, 126, 126);
            border-radius: 4px;
        /* テキスト設定 */
        text-align: center;
        text-decoration: none;
    }

    .card {
	animation: fadein 1s forwards;
    }

    @keyframes fadein {
	    0% {opacity: 0}
	    100% {opacity: 1}
    }

</style>

<div class="card">
    <h2 class="card-header">{{ base.name }} 座席</h2>
    <h4>　{{ start_day|date:"Y/n/j" }}</h4>
    <div class="panelbox2">
        {% for seat, schedule in calendar.items %}
            {% if forloop.counter > 0 and forloop.counter <= 10 %}
                {% for dt, schedule in schedule.items %}
                    {% if schedule == "none" %}
                        <a href="{% url 'app:booking' base.pk seat.pk dt.year dt.month dt.day %}">{{ seat }} ○</a>
                    {% else %}
                        <a href="{% url 'app:scheduledelete' sche.pop %}">{{ schedule }}</a>
                    {% endif %} 
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
    <div class="panelbox2">
        {% for seat, schedule in calendar.items %}
            {% if forloop.counter >= 11 and forloop.counter <= 20 %}
                {% for dt, schedule in schedule.items %}
                    {% if schedule == "none" %}
                        <a href="{% url 'app:booking' base.pk seat.pk dt.year dt.month dt.day %}">{{ seat }} ○</a>
                    {% else %}
                        <a href="{% url 'app:scheduledelete' sche.pop %}">{{ schedule }}</a>
                    {% endif %} 
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
    <div class="panelbox2">
        {% for seat, schedule in calendar.items %}
            {% if forloop.counter >= 21 and forloop.counter <= 30 %}
                {% for dt, schedule in schedule.items %}
                    {% if schedule == "none" %}
                        <a href="{% url 'app:booking' base.pk seat.pk dt.year dt.month dt.day %}">{{ seat }} ○</a>
                    {% else %}
                        <a href="{% url 'app:scheduledelete' sche.pop %}">{{ schedule }}</a>
                    {% endif %} 
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
</div>

</div>
{% endblock %}

project/app/templates/app/top.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}| 座席予約アプリ </title>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-success sticky-top">
      <div class="navbar-nav d-flex flex-row">
        {% if request.user.is_authenticated %}
          <a class="nav-link mx-3" href="{% url 'app:base_list' %}">拠点一覧</a>
          <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
        {% else %}
          <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
          <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>
        {% endif %}
      </div>
      <div align="right">
        <img src="/media/logo.jpg" width="80%" height="80%">
      </div>
    </nav>
    <div class='p-4'>
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>